"""initial schema

Revision ID: 25907f54ddd1
Revises:
Create Date: 2026-08-21 17:30:24.116283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25907f54ddd1'  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quota_usage',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('usage_date', sa.String(length=10), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('bonus_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'usage_date')
    )
    with op.batch_alter_table('daily_quota_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_quota_usage_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('invite_credentials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_credentials_code_digest'), ['code_digest'], unique=True)
        batch_op.create_index(batch_op.f('ix_invite_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('learning_sources',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('raw_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_sources_text_sha256'), ['text_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_sources_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_token_digest'), ['token_digest'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('generation_tasks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('voice_key', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['learning_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_tasks_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('programs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('transcript_json', sa.Text(), nullable=True),
    sa.Column('voice_key', sa.String(length=64), nullable=True),
    sa.Column('tts_model', sa.String(length=64), nullable=True),
    sa.Column('provider_voice_id', sa.String(length=128), nullable=True),
    sa.Column('audio_key', sa.String(length=255), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['learning_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_user_id'), ['user_id'], unique=False)

    op.create_table('provider_usage',
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('input_units', sa.Integer(), nullable=False),
    sa.Column('output_units', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_cny', sa.Float(), nullable=False),
    sa.Column('actual_cost_cny', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_steps',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_steps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_steps_step_name'), ['step_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_steps_task_id'), ['task_id'], unique=False)

    op.create_table('analytics_events',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_points',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_program_id'), ['program_id'], unique=False)

    op.create_table('recall_questions',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recall_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recall_questions_program_id'), ['program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recall_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recall_questions_program_id'))

    op.drop_table('recall_questions')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_program_id'))

    op.drop_table('knowledge_points')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_name'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('task_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_steps_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_steps_step_name'))
        batch_op.drop_index(batch_op.f('ix_task_steps_status'))

    op.drop_table('task_steps')
    op.drop_table('provider_usage')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_user_id'))
        batch_op.drop_index(batch_op.f('ix_programs_status'))
        batch_op.drop_index(batch_op.f('ix_programs_source_id'))

    op.drop_table('programs')
    with op.batch_alter_table('generation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_generation_tasks_source_id'))

    op.drop_table('generation_tasks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_digest'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('learning_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_sources_text_sha256'))

    op.drop_table('learning_sources')
    with op.batch_alter_table('invite_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_invite_credentials_code_digest'))

    op.drop_table('invite_credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('daily_quota_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_quota_usage_user_id'))

    op.drop_table('daily_quota_usage')
    # ### end Alembic commands ###
