"""add news sources, articles and programs

Revision ID: f211a45e3d6e
Revises: 25907f54ddd1
Create Date: 2026-08-21 18:35:48.021205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f211a45e3d6e'  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = '25907f54ddd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_programs',
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('program_date', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('transcript_json', sa.Text(), nullable=True),
    sa.Column('voice_key', sa.String(length=64), nullable=False),
    sa.Column('tts_model', sa.String(length=64), nullable=True),
    sa.Column('provider_voice_id', sa.String(length=128), nullable=True),
    sa.Column('audio_key', sa.String(length=255), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'program_date', name='uq_news_channel_date')
    )
    with op.batch_alter_table('news_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_programs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_programs_program_date'), ['program_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_programs_status'), ['status'], unique=False)

    op.create_table('news_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_sources_channel'), ['channel'], unique=False)

    op.create_table('news_articles',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_url'))
        batch_op.drop_index(batch_op.f('ix_news_articles_source_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_content_hash'))
        batch_op.drop_index(batch_op.f('ix_news_articles_channel'))

    op.drop_table('news_articles')
    with op.batch_alter_table('news_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_sources_channel'))

    op.drop_table('news_sources')
    with op.batch_alter_table('news_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_programs_status'))
        batch_op.drop_index(batch_op.f('ix_news_programs_program_date'))
        batch_op.drop_index(batch_op.f('ix_news_programs_channel'))

    op.drop_table('news_programs')
    # ### end Alembic commands ###
